export const GET_CARE_HOME_REQUEST = 'GET_CARE_HOME_REQUEST';
export const GET_CARE_HOME_SUCCESS = 'GET_CARE_HOME_SUCCESS';
export const GET_CARE_HOME_ERROR = 'GET_CARE_HOME_ERROR';

export const GET_PATIENT_DETAILS_REQUEST = 'GET_PATIENT_DETAILS_REQUEST';
export const GET_PATIENT_DETAILS_SUCCESS = 'GET_PATIENT_DETAILS_SUCCESS';
export const GET_PATIENT_DETAILS_ERROR = 'GET_PATIENT_DETAILS_ERROR';
